//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoMateria
    {
        public int id_AlumnoMaterias { get; set; }
        public Nullable<int> alumno_id { get; set; }
        public Nullable<int> materia_id { get; set; }
    }
}
