//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int id_alumno { get; set; }
        public string nombre_alumno { get; set; }
        public string apellido_alumno { get; set; }
        public string matricula_alumno { get; set; }
        public Nullable<bool> ingles_materia { get; set; }
        public Nullable<bool> espanol_materia { get; set; }
        public Nullable<bool> matematicas_materia { get; set; }
        public Nullable<bool> ciencias_materia { get; set; }
    }
}
