//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public int id_materia { get; set; }
        public string materia1 { get; set; }
    }
}
